owner: longhorn
repo: longhorn
token: ""
state: closed
note: >-
  ## Release Note

  ## Upgrade

  {content}
milestone: v1.1.1
show_contributor: true
extra_contributors:
  - innobead
any_labels: [ ]
labels: [ ]
exclude_labels:
  - area/test
  - kind/task
  - wontfix
highlight_labels:
  kind/bug:
    index: 2
    title: Bugs
  kind/enhancement:
    index: 1
    title: Enhancements
  highlight:
    index: 0
    title: Highlights
    description: ""
