owner: longhorn
repo: longhorn
token: ""
state: closed
note: >-
  ## Release Note
  ## Upgrade

  {content}
milestone: v1.1.1
show_contributor: true
any_labels: [ ]
labels: [ ]
exclude_labels:
  - area/test
  - kind/task
  - wontfix
highlight_labels:
  kind/bug: Bugs (index=2)
  kind/enhancement: Enhancements (index=1)
  highlight: Highlights (index=0)