owner: longhorn
repo: longhorn
token: ""
state: closed
note: >-
  # Release Note
  {content}
milestone: v1.1.1
show_contributor: true
any_labels: [ ]
labels: [ ]
exclude_labels:
  - kind/test
  - kind/task
  - wontfix
highlight_labels:
  - highlight
  - kind/enhancement
  - kind/bug
  - kind/upstream-issue