owner: longhorn
repo: longhorn
token: ""
state: all
note: >-
  ## Release Note

  ## Upgrade

  {content}
milestone: v1.1.1
show_contributor: true
extra_contributors:
  - innobead
any_labels: [ ]
labels: [ ]
exclude_labels:
  - area/test
  - kind/task
  - wontfix
highlight_labels:
  - label: highlight
    title: Highlights
    description: ""
  - label: kind/enhancement
    title: Enhancements
  - label: kind/bug
    title: Bugs

