---
owner: longhorn
repo: longhorn
token: ""
state: closed        # open, closed, all
note: >-             # string or file path
  ## Release Note
  {content}

milestone: v1.1.1
show_contributor: true
extra_contributors:
  - innobead
exclude_issues:
  - 304
  - 508
  - 1701
sort: asc            # asc, desc
labels: []
any_labels: []
exclude_labels:
  - area/test
  - area/test-infra
  - kind/task
  - kind/environment-issues
  - wontfix
highlight_labels:
  - label: highlight
    title: Highlights
    description: ~
  - label: kind/enhancement
    title: Enhancements
    description: ~
  - label: kind/bug
    title: Bugs
    description: ~
