name: test
draft: true
pre_release: true
artifacts: []
search_issue_config:
  owner: longhorn
  repo: longhorn
  token: ""
  state: all
  note: ""
  milestone: v1.1.1
  labels: [ ]
  exclude_labels: [ ]
  highlight_labels:
    - highlight
    - kind/enhancement
    - kind/bug
    - kind/upstream-issue
