name: Build

on:
  workflow_dispatch:
    inputs:

jobs:
  build-linux-x86_64:
    name: Build for Linux x86_64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup build environment
        run: make setup-dev

      - name: Run tests
        run: make test

      - name: Build all artifacts
        run: make build

  build-macos:
    name: Build for MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup build environment
        run: make setup-dev

      - name: Run tests
        run: source ~/.bashrc && make test

      - name: Build all artifacts
        run: source ~/.bashrc && make build
